ignore_build_only_deps:
- python
- numpy
extend_keys:
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
- ignore_version
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
bzip2:
- '1.0'
lua:
- '5'
noarch_python:
- python
gst_plugins_base:
- '1.14'
libgd:
- 2.2.5
mkl:
- '2019'
c_compiler:
- gcc
rust_compiler:
- rust
libxslt:
- '1.1'
mpfr:
- '4'
python:
- '3.9'
fortran_compiler_version:
- 7.3.0
gnu:
- 2.12.2
macos_machine:
- x86_64-apple-darwin13.4.0
cxx_compiler:
- gxx
libprotobuf:
- 3.11.2
libgsasl:
- '1.8'
r_base:
- '3.5'
libxml2:
- '2.9'
cyrus_sasl:
- 2.1.26
clang_variant:
- clang
xz:
- '5'
python_impl:
- cpython
libpng:
- '1.6'
cpu_optimization_target:
- nocona
gstreamer:
- '1.14'
hdfeos5:
- '5.1'
c_compiler_version:
- 7.3.0
nodejs:
- '8.12'
proj4:
- 5.2.0
boost:
- '1.73'
libwebp:
- 1.0.0
hdf4:
- '4.2'
blas_impl:
- openblas
- mkl
zlib:
- '1.2'
hdf5:
- 1.10.6
jpeg:
- '9'
harfbuzz:
- '2.4'
macos_min_version:
- '10.9'
apr:
- 1.6.3
target_platform:
- linux-64
serf:
- 1.3.9
VERBOSE_AT:
- V=1
openblas:
- 0.3.3
pixman:
- '0.34'
libtiff:
- '4.1'
perl:
- '5.26'
libffi:
- '3.3'
numpy:
- '1.16'
fortran_compiler:
- gfortran
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
qtwebkit:
- 'true'
fontconfig:
- '2.13'
libnetcdf:
- '4.6'
tk:
- '8.6'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
VERBOSE_CM:
- VERBOSE=1
libgdal:
- '3.0'
boost_cpp:
- '1.73'
cairo:
- '1.14'
freetype:
- '2.10'
sqlite:
- '3'
channel_targets:
- defaults
libdap4:
- '3.19'
rust_compiler_version:
- 1.46.0
proj:
- 6.2.1
geos:
- 3.8.0
readline:
- '8.0'
cxx_compiler_version:
- 7.3.0
libkml:
- '1.3'
g2clib:
- '1.6'
lzo:
- '2'
openssl:
- 1.1.1
python_implementation:
- cpython
giflib:
- '5'
expat:
- '2.2'
gmp:
- '6.1'
icu:
- '58'
openjpeg:
- '2.3'
glib:
- '2'
r_version:
- 3.5.0
r_implementation:
- r-base
- mro-base
hdfeos2:
- '2.20'
dbus:
- '1'
llvm_variant:
- llvm
zip_keys: []
