# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Dec  7 19:38:15 2020
# ------------------------------------------------

package:
    name: tqdm
    version: 4.54.1
source:
    sha256: 38b658a3e4ecf9b4f6f8ff75ca16221ae3378b2e175d846b6b33ea3a20852cf5
    url: https://pypi.io/packages/source/t/tqdm/tqdm-4.54.1.tar.gz
build:
    entry_points:
        - tqdm = tqdm.cli:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/tqdm_1607369919789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.12.5 py39h06a4308_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.3 py39h06a4308_0
        - python 3.9.0 hdb3f193_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.2 py39h06a4308_2
        - setuptools-scm 4.1.2 py_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - toml 0.10.1 py_0
        - tzdata 2020d h14c3975_0
        - wheel 0.36.0 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=2.7
test:
    commands:
        - pip check
        - tqdm --help
        - tqdm -v
    imports:
        - tqdm
    requires:
        - pip
about:
    dev_url: https://github.com/tqdm/tqdm
    doc_url: https://github.com/tqdm/tqdm
    home: https://pypi.python.org/pypi/tqdm
    license: MPL-2.0 or MIT
    license_family: MIT
    license_file: LICENCE
    summary: A Fast, Extensible Progress Meter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - casperdcl
        - ericdill
        - pmlandwehr
